version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_PATH: http://localhost:8080
    restart: always
    ports:
      - 3333:80

  backend:
    build:
      .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/timertracker
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pw

  db:
    image: postgres
    restart: always 
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: timertracker
